apiVersion: v1
kind: ConfigMap
metadata:
  name: autocorp-config
data:
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  GMAIL_CREDENTIALS_FILE: "/secrets/credentials.json"
  GMAIL_TOKEN_FILE: "/secrets/token.json"
  CALENDAR_CREDENTIALS_FILE: "/secrets/credentials.json"
  CALENDAR_TOKEN_FILE: "/secrets/calendar_token.json"
  GCS_BUCKET: "emp-docs-bucket"
  PGHOST: "host.docker.internal"
  PGPORT: "5432"
  PGDATABASE: "hr"
  PGUSER: "postgres"
